# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
src = "contracts"
test = "tests"
script = "scripts"
out = "out"
libs = ["lib"]
remappings = [
    "@interfaces/=interfaces/",
    "@contracts/=contracts/",
    "@deployments/=contracts/global/arbitrum/"
]
evm_version = "shanghai"
fs_permissions = [
  { access = "read-write", path = "./scripts/deploy"},
  { access = "read", path = "./out_arbitrum"},
  { access = "read", path = "./out_mainnet"},
]

[profile.arbitrum]
chain_id = 42161
out = "out_arbitrum"
remappings = [
    "@interfaces/=interfaces/",
    "@contracts/=contracts/",
    "@deployments/=contracts/global/arbitrum/"
]
libraries = [
  "@contracts/vaults/common/StrategyUtils.sol:StrategyUtils:0x863C4B7C2c78CA1C6C8Ba644d1f34476F37922e4"
]

[profile.mainnet]
chain_id = 1
out = "out_mainnet"
remappings = [
    "@interfaces/=interfaces/",
    "@contracts/=contracts/",
    "@deployments/=contracts/global/mainnet/"
]
libraries = [
  "@contracts/vaults/common/StrategyUtils.sol:StrategyUtils:0xE78D09c8B6cCF9C1732d14353a708b75f6C67c67"
]
